.PHONY: clean All

All:
	@echo "----------Building project:[ working - Debug ]----------"
	@"$(MAKE)" -f  "working.mk"
clean:
	@echo "----------Cleaning project:[ working - Debug ]----------"
	@"$(MAKE)" -f  "working.mk" clean
