version: '3.3'
services:
  sqlserver:
    build:
      context: .
    container_name: sqlserver
    environment:
      SA_PASSWORD: 'sql123456@@'
      ACCEPT_EULA: 'Y'    
    ports:
      - 1433:1433
#    volumes:
#      - /d/desenvolvimento/dev-resources/sql:/var/opt/mssql/data
