@IMBD_HostAddress = https://localhost:5001
@MovieId = 68dd8b45352fd8d641bc5755

###

### Obter filme com reviews páginado
GET {{IMBD_HostAddress}}/movies/{{MovieId}}/reviews?skip=100&limit=5000
Accept: application/json

### Obter filme
GET {{IMBD_HostAddress}}/movies/{{MovieId}}
Accept: application/json
X-Api-Key: minha-chave

### Obter estatisticas do filme
GET {{IMBD_HostAddress}}/movies/{{MovieId}}/stats
Accept: application/json

### Obter filmes
GET {{IMBD_HostAddress}}/movies/
Accept: application/json
X-Api-Key: minha-chave

### Inserir filme
POST {{IMBD_HostAddress}}/movies/
Content-Type: application/json

{
  "title": "The Matrix",
  "year": 1999,
  "releaseDate": "1999-03-31T00:00:00Z",
  "castings": ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"]
}

### Criar Reviews fake
POST {{IMBD_HostAddress}}/movies/{{MovieId}}/reviews/seed/20000
###